# Generated by Django 5.0.6 on 2024-09-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('United Kingdom', 'United Kingdom')], default='United Kingdom', max_length=254),
        ),
    ]
