# Generated by Django 5.0.6 on 2024-06-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_origin',
            field=models.CharField(default='United Kingdom', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='country_testing',
            field=models.CharField(default='United States', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='purity',
            field=models.DecimalField(decimal_places=2, default=98.0, max_digits=6),
        ),
    ]
