# Generated by Django 5.0.6 on 2024-06-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_country_origin_product_country_testing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
    ]
